### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by HCWDavid** [pytorch/captum#1038]
Hi,

for some reason, I can not import 

`captum.attr.visualization` based on the [utilities](https://captum.ai/api/utilities.html) link

both `visualize_timeseries_attr` and `visualize_image_attr` would not work. I am wondering if I did something wrong? if not, could it be fixed on the document to know how to do it?

And I tried `captum.attr._utils.visualization` this, and it works only on `visualize_image_attr` but not `visualize_timeseries_attr`

Thank you!

**Comment by NarineK** [comment]
@HCWDavid, have you tried to import it like this ? 
```
from captum.attr import visualization as viz
```
similar to this tutorial:
https://captum.ai/tutorials/Resnet_TorchVision_Interpret 

What is the import error that you see ?

**Comment by vivekmig** [comment]
Hi @HCWDavid , the issue with visualize_timeseries_attr is likely due to the method being recently added, so it was not included in the previous pip / conda releases, and will be available in the next release. 

To utilize this functionality in the meantime, you would need to install Captum from source. To do this, you can follow the Manual / Dev Install instructions [here](https://github.com/pytorch/captum#installation). Hope this helps!

**Comment by vivekmig** [comment]
Closing this issue, feel free to open another one if there are further issues.
