### ISSUE TITLE
Understand how baselines parameter from attribute()  is used during Occlusion for 2D images

### ISSUE THREAD

**Issue by Pamasi** [pytorch/captum#1099]
## ❓ Questions and Help

Hi,
I wonder how Captum use the _baselines_ in _Occlusion_ class when _inputs_ is a batch of a grayscale image e.g. shape  of inputs tensor (1,1,416,512) . If  _baselines_ is a tensor the documentation say that it must have _same dimensions as inputs or broadcastable to match the dimensions of inputs_, which means that some portion of baselines are used to replace the original pixel value of the image inside the batch or all values from the tensor _baselines_ are used at the same time for every occlusion that is done?

**Comment by Pamasi** [comment]
![image](https://user-images.githubusercontent.com/46300254/211149273-cf08bf7b-4058-4c44-a280-cb09d9faa0c5.png)

After some some debug I finally understood how it works, but  I will left a comment hoping that would clarify it:
basically after the input mask related to pixel-tensor to be occluded has been calculated, they are replaced with pixels in baseline that have the same coordinates as it can be seen from last line before return of the method in the image (which is  responsible for ablation in Occlusion).

**Comment by NarineK** [comment]
Hi @Pamasi, sorry for the late reply. As you already found the code pointer correctly, the occluded patch takes baseline values corresponding to the pixel positions in the original input. Broadcasting here is similar to other high dimensional tensor broadcasting. 
By default zero-valued baseline is used. If the baseline is a scalar then we use that for all occluded pixels otherwise positions are mapped in original and baseline inputs and the values are copied only for the correct positions when performing occlusion. 

You can also check out our test cases as simple examples:
https://github.com/pytorch/captum/blob/master/tests/attr/test_occlusion.py#L218
