### ISSUE TITLE
Does Captum support multivariate regression? 

### ISSUE THREAD

**Issue by csqray** [pytorch/captum#1126]
I have multiple continues outputs to predict and want to figure out the relationship between input and each variable in the output.

**Comment by aobo-y** [comment]
@csqray It supports, but this may depend on the actual algorithm you want to use.

If you are using basic `FeatureAblation` and `FeaturePermutation`, you can simply return multiple variables in the forward output. Assuming forward function's output is in shape `[batch_size, N]` while input in shape `[batch_size, X]`, these two methods will return a tensor in shape `[batch_size * N, X]`. Every row of `batch_size * N` means the feature attribution of X with respect to an output variable.

If you are using `IntegratedGradient`, since Captum will back-propagate from the return of the forward function, you have to run the attribution multiple times, in each of which your forward function should only return one output variable for captum to calculate the gradients of input.
