### ISSUE TITLE
None of your tutorial links work and the pytorch colab is broken

### ISSUE THREAD

**Issue by loftusa** [pytorch/captum#1202]
First: https://pytorch.org/tutorials/recipes/recipes/Captum_Recipe.html
If you go there and open up the colab, `captum` is not pip installed inside the colab link (the user has to install it manually) and the visualization code is broken.

Second: https://captum.ai/tutorials/
Literally all of the links to the tutorials here are broken.

**Comment by vivekmig** [comment]
Hi @loftusa , thanks for reporting this issue! The tutorials on captum.ai were broken due to an issue with our website deployment pipeline, this has now been resolved, thanks for letting us know!

For the PyTorch tutorial, the visualization issue has been fixed and will be in the next version of Captum which will be released shortly. In the meantime, this can be resolved by installing captum from source in Colab with `pip install git+https://github.com/pytorch/captum.git` (see #1165).

**Comment by vivekmig** [comment]
Captum 0.7 has now been released, so the visualization issue should also be resolved.
