### ISSUE TITLE
Issue with resnet18 model

### ISSUE THREAD

**Issue by cjbarb7** [pytorch/captum#236]
I tried to use any of the saliency methods and I get this error:
AttributeError: 'AvgPool2d' object has no attribute 'divisor_override'

Do not understand why that happens?

**Comment by vivekmig** [comment]
Hi @cjbarb7 , this issue sounds specific to your model, so we'll likely need more information to debug this. From the error given, it seems like it could be related to PyTorch versions or the AvgPool2d object not being created appropriately, since the divisor_override attribute seems to be set by the constructor of AvgPool2d in recent versions of PyTorch. Can you first double-check that just running a forward and backward pass of your model work without any errors? For instance, for a single input tensor, this would be something like:
```
# Forward pass
outputs = model(input)

# Backward pass
# Note if you have multiple outputs per input, 
# you will have to select one column of outputs first.
torch.autograd.grad(torch.unbind(outputs), input)
```
If either gives you the same error, there may be something with your model that needs to be fixed. If both of these work fine, we can look into this further with some more details about your model and the full stack trace. Thanks!

**Comment by cjbarb7** [comment]
Sorry for the late reply. Thanks for the tip, yea something is wrong with the model.
