### ISSUE TITLE
Dealing with .view in DeepLift

### ISSUE THREAD

**Issue by tsKenneth** [pytorch/captum#257]
Hi, I am an undergrad student looking to apply Captum's implementation of DeepLift for a Graph Convolution Network

Below is a snippet of the code in the forward function that is causing problems:
```
to_conv1d = batch_sortpooling_graphs.view((-1, 1, self.k * self.total_latent_dim))
    conv1d_res = self.conv1d_params1(to_conv1d)
    conv1d_res = self.conv1d_activation(conv1d_res)
    conv1d_res = self.maxpool1d(conv1d_res)
    conv1d_res = self.conv1d_params2(conv1d_res)
    conv1d_res = self.conv1d_activation(conv1d_res)

    to_dense = conv1d_res.view(len(graph_sizes), -1)

    if self.output_dim > 0:
        out_linear = self.out_params(to_dense)
        reluact_fp = self.conv1d_activation(out_linear)
    else:
        reluact_fp = to_dense
    return self.conv1d_activation(reluact_fp)
```

As you can see, my code requires several reshapes of the tensors as it moves from the input to the 1d convolution layer and finally to the dense layer. Running as is gives me the following error:

```
Traceback (most recent call last):
  File "main.py", line 625, in <module>
    attribution = dl.attribute(input, additional_forward_args=[15], target=1)
  File "/home/soggeh/.local/lib/python3.6/site-packages/captum/attr/_core/deep_lift.py", line 202, in attribute
    additional_forward_args=additional_forward_args,
  File "/home/soggeh/.local/lib/python3.6/site-packages/captum/attr/_utils/gradient.py", line 92, in compute_gradients
    grads = torch.autograd.grad(torch.unbind(output), inputs)
  File "/home/soggeh/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 157, in grad
    inputs, allow_unused)
  File "/home/soggeh/.local/lib/python3.6/site-packages/captum/attr/_core/deep_lift.py", line 284, in _backward_hook
    inp - inp_ref for inp, inp_ref in zip(module.input, module.input_ref)
  File "/home/soggeh/.local/lib/python3.6/site-packages/captum/attr/_core/deep_lift.py", line 284, in <genexpr>
    inp - inp_ref for inp, inp_ref in zip(module.input, module.input_ref)
RuntimeError: The size of tensor a (160) must match the size of tensor b (19) at non-singleton dimension 2
```

The shapes of each tensors are as follows:

```
batch_sortpooling_graphs: torch.Size([1, 19, 97])
conv1d_res (immediately after line 1): torch.Size([1, 1, 1843])
to_dense: torch.Size([1, 160])
```

May I ask if anyone has any idea how to circumvent this such that the DeepLift can work with tensor reshapes? Thank you!

**Comment by NarineK** [comment]
Hi @tsKenneth, thank you for trying out captum! 
I think the problem is that the shape of baseline doesn't match with the shape of input for some activations. Did you specify input baseline or do you use default baseline ? If not then zero-valued tensor is used.
One way to debug is to compare the output sizes for the input and baseline. If you run the forward pass on your network using the baselines as inputs do you get the same shape ?

Another issue I see is that you are reusing `self.conv1d_activation`, for example. If we reuse the activations it won't work as expected. To support that we need to consider JIT and graph representation. Could you redefine a new one instead of reusing `self.conv1d_activation` ?

**Comment by tsKenneth** [comment]
Thanks @NarineK for the prompt help!
I was using default zero-valued tensor.

Redefining `self.conv1d_activation` solved the problem. I understand this question is now a duplication of #200 . Thank you so much!
