### ISSUE TITLE
Import error for Occlusion

### ISSUE THREAD

**Issue by chauhang** [pytorch/captum#292]
Getting import error for Occlusion on running the tutorial [Interpreting vision for Resnet](https://captum.ai/tutorials/Resnet_TorchVision_Interpret).

**Error details**
ImportError                               Traceback (most recent call last)
<ipython-input-26-2ef44b802092> in <module>
     15 from captum.attr import IntegratedGradients
     16 from captum.attr import GradientShap
---> 17 from captum.attr import Occlusion
     18 from captum.attr import NoiseTunnel
     19 from captum.attr import visualization as viz
ImportError: cannot import name 'Occlusion' from 'captum.attr' (/home/ubuntu/opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/captum/attr/__init__.py)

**Comment by NarineK** [comment]
Hi @chauhang ! 

Thank you for the issue. We haven't released the new version yet. Occlusion is one of the recent algorithms that we have added. The release will happen by the end of Feb, that's why we recommend to install the dev version.

The instructions are under: Manual / Dev install
https://github.com/pytorch/captum

Let me know if that works for you!

**Comment by NarineK** [comment]
@chauhang , did the dev version work for you ? If so, can we close the issue ?

**Comment by NarineK** [comment]
closing this since we released new version and it should work as expected.
