### ISSUE TITLE
Attribution Analysis on a Regression network

### ISSUE THREAD

**Issue by hemanthkorrapati** [pytorch/captum#482]
I am trying to perform attribution analysis on a regression network whose input is a list of tensors and output is list of tensors. I looked at the `LayerIntegratedGradients` class and the target format seems to be geared towards a classification network that outputs a single variable or a 1-of-K output. Is it possible at all to use `LayerIntegratedGradients` on a regression network ? If so how to format the network output and target ?

**Comment by vivekmig** [comment]
Hi @hemanthkorrapati , you should definitely be able to use LayerIntegratedGradients on a regression network. Since your model returns a list of tensors, you'd likely need to define a wrapper function which selects a particular tensor of the output list to compute attributions for. 

This can be done as follows:
```
model = MultiOutputModel()
def model_wrapper(*inps):
    model_out = model(*inps)
    return model_out[selected_tensor_index]

layer_attr = LayerIntegratedGradients(model_wrapper, model.chosen_layer)
layer_attr.attribute(...)
```

Attributions must be performed with respect to a scalar value per input example, so if the chosen tensor contains multiple outputs, you can still use the target argument to choose the appropriate column or elements of the output tensor. Our FAQ answer [here](https://captum.ai/docs/faq#how-do-i-set-the-target-parameter-to-an-attribution-method) also has more context on setting the target parameter appropriately. Hope this helps!

**Comment by hemanthkorrapati** [comment]
Thanks @vivekmig!! Although the information was helpful it took some effort to get it to work. Mainly because I was not using the additional_args parameter and instead passing all my input parameters for attribution analysis. And some of our inputs are binary which resulting in gradients being None. So I had to edit the captum code to make sure that NoneType gradients are ignored. However making sure that passing the additional arguments properly resolved the issue.

**Comment by RylanSchaeffer** [comment]
@vivekmig quick question: how does one use `VisualizationDataRecord` with a regression task? Some slots are `pred_class` and `true_class`, which don't seem applicable.

**Comment by RylanSchaeffer** [comment]
Is there a tutorial somewhere?
