### ISSUE TITLE
Gradcam for 3D object detection architecture for point cloud 

### ISSUE THREAD

**Issue by abhigoku10** [pytorch/captum#488]
## 🚀 Feature

Can we apply grad cam / score cam for architecture or model which perform detection / segmentation on point cloud data

**Comment by bilalsal** [comment]
Hi @abhigoku10 ,

CAM methods are designed to interpret classification decisions and require that you specifying a target class in order to determine which the parts of the image support this class (sort of, localize the decisions).

Object detection architectures usually perform both localization and classification, either in two phases such as in the RCNN framework, or in one integrated phase such as in SSD / YOLO detectors. In these detectors, there are no proper Class Activation Maps, therefore CAM approaches are not applicable.
You can still perform [Neuron Attribution algorithms](https://captum.ai/api/neuron.html) such as [Neuron Integrated Gradient](https://captum.ai/api/neuron.html#neuron-integrated-gradients) or [Neuron Gradient](https://captum.ai/api/neuron.html#neuron-gradient) to analyze what the neurons in certain layers respond to (say, in the final layer of the backbone CNN).

For semantic segmentation, you can have a look at [this tutorial](https://captum.ai/tutorials/Segmentation_Interpret) which uses Layer Attribution (in particular, [LayerGradCam](https://captum.ai/api/layer.html#gradcam)) after defining a wrapper to the model to convert per-class segmentation maps into scalar class outputs which Captum can handle.

Hope this helps

**Comment by abhigoku10** [comment]
@bilalsal  thanks for the response , i wanted to knw if caputm-gradcam can be used for 3D point cloud based architecture models like detection classification or segmentation , if so what would be the changes required
