### ISSUE TITLE
Question about using Captum with custom model for colourisation.

### ISSUE THREAD

**Issue by Riretta** [pytorch/captum#537]
Hi,
I would like to use Captum with my custom model. My model takes as input a matrix [Batch,1,H,W] and return a [Batch,2,H,W] so it is not classification but colourisation and my target is a matrix of the same dimension as output. I tried with the library, but I understood that it is usable for classification and regression, is it? 

If I can use Captum in some ways that are not evident to me, just please help me understand.

**Comment by bilalsal** [comment]
Hi @Riretta ,

Captum does not actually assume your model is performing classification. However, it currently only support attributing a *scalar* output to the input. Since your output is effectively 3D (A/B color coordinates,  H, W), it is indeed not straightforward to perform attribution. We need to think about, what (scalar) aspect of the output we want to attribute to the input.
You can define a wrapper of your colourisation model to capture this aspect, and use Captum to perform attribution on this wrapper.
For example, the wrapper can sum up the 2D output for each of your two color coordinates.
```
def wrapper(inp):
    return torch.sum(model(inp), axis = (2, 3))
```

Then you can use Captum to determine which parts of the input contribute to A colors and which parts give rise to B colors.
```
ig = IntegratedGradient(wrapper)
attribution_A = ig.attribute(img.unsqueeze(0),target=0, ...) 
attribution_B = ig.attribute(img.unsqueeze(0),target=1, ...) 
```

Another wrapper can sum up all output values within a specific image patch. Then Captum can compute which input parts influence the colorization of this patch (I would expect the corresponding input patch will have the most contribution, but neighboring ones could also have an influence, e.g., the presence of trees will influence colorization of sky-like areas).

You can refer to our [Segmentation Tutorial](https://captum.ai/tutorials/Segmentation_Interpret) or to #377 for inspiration on aspects of spatial output you can attribute to the input using wrappers.

Hope this helps
