### ISSUE TITLE
Question for Runtime error of Deeplift

### ISSUE THREAD

**Issue by tylee0325** [pytorch/captum#578]
Hi, thank you for supporting this nice library. 
I tried to apply deepLift to my seq2seq model which including LSTM and transformer. 

and I got a Runtime error for the ReLU module. 
As described in the code, I tried changing from nn.ReLU() to nn.ReLU(inplace=False). But it failed. 

It seems I cannot reuse the module in the network.
I tried to understand the meaning of the error message but I couldn't. 

1. how can I solve this Runtime error? How can I use ReLU module properly?
2. Is it possible using DeepLift on RNNs network? (I hope so..)

thank you. 

Below is what I got as Runtime Error. 
```python 
    def _backward_hook(
        ... 
        # before accessing the attributes from the module we want
        # to ensure that the properties exist, if not, then it is
        # likely that the module is being reused.
        attr_criteria = self.satisfies_attribute_criteria(module)
        if not attr_criteria:
            raise RuntimeError(
                "A Module {} was detected that does not contain some of "
                "the input/output attributes that are required for DeepLift "
                "computations. This can occur, for example, if "
                "your module is being used more than once in the network."
                "Please, ensure that module is being used only once in the "
                "network.".format(module)
            )
```

**Comment by NarineK** [comment]
Hi @tylee0325, thank you for the questions! 

1. In terms or RELU - you can use RELUs with in_place = True or in_place= False but you cannot reuse them. You need to redefine them because in the module hooks we do not know exactly where the RELU is called in the computation graph. This is work in progress.   
2. As described in the documentation we do not support RNN, LSTM etc. for DeepLift because in PT we cannot access the building blocks of LSTM, RNN etc.
https://github.com/pytorch/captum/blob/master/captum/attr/_core/deep_lift.py#L101
