### ISSUE TITLE
ZERO SHOT MODELS 

### ISSUE THREAD

**Issue by ajay01994** [pytorch/captum#596]
Hi Team ,

Thanks for releasing captum , I was looking for tutorial or use case for interpretation  and  gradient visualization  of zero shot BERT /BART models for specific tasks , can you please guide me how to do that , I am fairly new to captum , would appreciate any help in this regards 

Thank you !

Ajay Sahu

**Comment by bilalsal** [comment]
Hi @ajay01994 ,

Maybe try to follow [the BERT]( https://captum.ai/tutorials/Bert_SQUAD_Interpret) tutorial?

Generally speaking, Captum operates on a model regardless of how it was is trained. This means Captum should be able to compute attributions for classes that had zero training samples.

Hope this helps

**Comment by ajay01994** [comment]
Ok i see, i tried for BART, but there aren't any tutorials for BART can you please provide some insights over it.. BERT tutorials can't be used in it.. Also please can you make captum a bit simpler so that earlie birdies  can.. Experiment with it more

Thanks 

Ajay sahu

**Comment by bilalsal** [comment]
Hi @ajay01994,

yes interpreting BERT / BART models can be tricky, especially because we need to link the embedding layer with the tokens. In https://github.com/pytorch/captum/issues/592#issuecomment-768612690, @NarineK proposed a simplified route to compute the attributions. Maybe this makes it easier to work with BART?

Hope this helps

**Comment by subhamkhemka** [comment]
Hi @ajay01994,

Have you figured out how to use captum for zero shot models ? If yes do you have an example which would be helpful.
