### ISSUE TITLE
Error while using baselines for GradientShap

### ISSUE THREAD

**Issue by pupul07** [pytorch/captum#722]
## ❓ Questions and Help

We have a set of listed resources available on the website and FAQ: https://captum.ai/ and https://captum.ai/docs/faq . Feel free to open an issue here on the github or in our discussion forums:

- [Discussion Forum](https://discuss.pytorch.org/c/captum)

Hello everyone! I am a new user of Captum (started last month!). I have an RNN-based model that takes as input three tensors: (N, 257), (N ,12, 73) and (1, N, 36) where N is the total number of examples.

I am calculating integrated gradients as follows:
```
ig = IntegratedGradients(rnn9c)
N = len(X_static_tests[b_id])
static_baseline = torch.unsqueeze(X_static_tests[b_id].mean(axis=0),0)
dynamic_baseline = torch.unsqueeze(X_dynamic_tests[b_id].mean(axis=0),0)
h0_baseline = torch.unsqueeze(h0_tests[b_id].mean(axis=1),0)
attr, delta = ig.attribute((X_static_tests[b_id], X_dynamic_tests[b_id], h0_tests[b_id]),
                           (static_baseline.repeat(N,1), dynamic_baseline.repeat(N,1,1), h0_baseline.repeat(1,N,1)),
                           n_steps = 100, return_convergence_delta=True)
```

This works! However, I wanted to compare my IG attributions with GradSHAP attributions so I tried using GradSHAP instead:

```
gshap = GradientShap(rnn9c)
shap_values = gshap.attribute((X_static_tests[b_id], X_dynamic_tests[b_id], h0_tests[b_id]),
                               (static_baseline.repeat(N,1), dynamic_baseline.repeat(N,1,1), h0_baseline.repeat(1,N,1)))
```

Now I get an error that says:
```
--> 413     rand_coefficient = rand_coefficient.view(inp_shape)

RuntimeError: shape '[5, 1, 1]' is invalid for input of size 5000
```

I'm not sure what I'm doing wrong! Can anybody help? :)

**Comment by bilalsal** [comment]
Thank you very much for reporting this, @pupul07 !

GradientShap indeed has its [own method to apply baselines](https://github.com/pytorch/captum/blob/master/captum/attr/_core/gradient_shap.py#L416), and this method seems to expect that all inputs in your tuple have the same batch size ([it is inferring this size from the first element](https://github.com/pytorch/captum/blob/master/captum/attr/_core/gradient_shap.py#L361) `inputs[0]`).
This probably explains why `IntegratedGradients` worked while `GradientShap` did not.

If your have to deal with inputs of varying batch sizes, a quick workaround would be to call GradientShap.attribute() individually with each of them (instead of using a tuple).

@vivekmig : Would it be feasible to support inputs of varying batch sizes in `GradientShap`?  

Hope this helps

**Comment by NarineK** [comment]
@pupul07, GradientShap chooses a point between input and baseline and it assumes that the first dimension of your input is batch size. `rand_coefficient ` assumes that your first dimension is batch size as well. In order to find a workaround  you can define a custom forward function takes inputs transposed the way so that it has first dimension as batch size. In the custom forward function you can transpose it back and call your model:

```
# input dims: (N, 257), (N ,12, 73) and (1, N, 36)
def my_forward_func(inp1, inp2, inp2): 
   return model(inp1, inp2, inp3.view(inp3.shape[1], inp3.shape[0], inp3.shape[2]))

```

Call attribute with something like this:
```
gs.attribute(inp1, inp2, inp3.view(inp3.shape[1], inp3.shape[0], inp3.shape[2]), base1, base2, base3.base3(base3.shape[1], base3.shape[0], base3.shape[2]))
```
Let me know if this worked for you.
