### ISSUE TITLE
Single importance value of a layer?

### ISSUE THREAD

**Issue by R-N** [pytorch/captum#735]
My model has two branches; one of them is shared with another model. I'd like to compare the two branch importance by attribution. They have identical architecture but different neuron count, so a difference in output size in last dimension. I use GradCam layer attribution and I get tensor of the same size as each branch's output. How do I get a single value from the tensor to compare their importance? Do I just sum the attribution output? Or average them with the neuron count? 

What about the batch size and output length? The input is of dimension (batch, length, feature) (it's forecasting). Is it possible to have it be comparable to another model with different batch size or forecast horizon (length)?

There's another branching that uses LSTMCell. The LSTMCell is used in a loop with the dimension being (batch, feature). How does this affect the attribution? Will my single value from before be comparable to the one from LSTMCell?

Also, the attribution on LSTMCell is different; it doesn't have the same size and dimension as the output tensor. I set the output size to be at least 3 and torchinfo confirms the model to be correct, but the attribution always only have 1 (for the last dimension). Why? Is this the correct behavior?

Thanks

**Comment by bilalsal** [comment]
Hi @R-N,

Yes it is possible to sum-up the attributions you get for each branch in order to assess how important each branch is when computing the model's output for a given input.
Note that such "important score" can be different for different inputs. For example certain inputs might indeed rely on branch 1 while other inputs might mainly rely on branch 2.
For the above reason, I would recommend that you compute the above "importance score" per sample, i.e., with. batch-size = 1.
Once compute for a large number of samples, you might observe that one branch is systematically more important than the other.
I also recommend you compute the sum, not the average per neuron, even if your branches have different output sizes. Your model relies on the entire output of a branch in further calculations, and summation does account for this.

The above should also apply when your branches are LSTMCell(s). It might not less useful to compare the attribution values you get using such branches with the ones you get in the previous case, however, you can still compare the contribution of the two parallel branches to each other.

Generally, the attribution size is equal to the _input size_, not the output size. Does this help explain the sizes you got when using LSTMCell?

Hope this helps

**Comment by R-N** [comment]
Thanks, I will just do that. 

However, regarding LSTMCell, I thought **layer** attribution size will mimic the output size of the layer (since it's also the size of the neurons)? Even if it mimics input, it's still shouldn't be 1. It accepts input of size of 6-30 and should output size of 3-10. 

Maybe my usage of LSTMCell affects this? LSTMCell outputs hx and cx, but because Captum requires all tensor to have gradients, I wrap the LSTMCell to have its output reversed (cx then hx) and only output cx in the last iteration. Captum now only attributes cx (I expected both cx and hx but this is fine) but the size doesn't match (weird).

Sorry for my late response, I've been quite busy and missed the email notification.

**Comment by R-N** [comment]
@bilalsal  I see. Well, I've tried on layers before and after LSTMCell and the attribution shape mimics the output shape as expected. Maybe the LSTMCell recurrent nature and the wrapper indeed affects the shape, even though the wrapper really doesnt modify the tensor at all. 

Is it fine to just use the attribution despite this weird behavior though? The shape doesn't really matter to me since I will just sum it anyway. I'm just worried if it's faulty somehow.

**Comment by bilalsal** [comment]
Hi @R-N,

yes I do not see any issue with using the attribution results as you described.
I hope you find the results informative for your use case.
We often iterate on the solution until we reach robust attribution results, trying different Captum algorithms, baselines, and parameters (e.g. n_steps).
The goal of Captum is to make such iteration and analysis as seamless as possible.

Best of success with your use case!
Bilal

**Comment by R-N** [comment]
Okay then, thanks @bilalsal!
Closing this issue
