### ISSUE TITLE
How can I use captum for custom deep learning model that includes structure data and text data?

### ISSUE THREAD

**Issue by Dongzhanghit** [pytorch/captum#825]
Recently, I have been focusing on fake news detection. The data includes users characteristics (structure data) and text data. I'm trying to build a hybrid model to detect fake news. More specifically, I use BERT for embedding the text data and then combined with user characteristic data? So, how can I leverage captum for visualizing the feature importance of both structure data and text data? Furthermore, how can I identify the contributions of words in the combined model?

**Comment by sid-sundrani** [comment]
@bilalsal hey.. have a question on similar lines. how do you recommend dealing with categorical and continous features part of the model input? For example, if input into the nn model is [cat_feature, continous_feature]. Inside the model, there is an embedding layer that gets the embedding for the cat_feature. Would you recommend separating the embedding and the model, getting the embedding of the categorical feature separately and input to the model in `ig.attribute` is just the continoous features? 

Or is there a way to make it work without doing this separately? I took a look a the `configure_interpretable_embedding_layer` example [here](https://github.com/pytorch/captum/blob/38b57082d22854013c0a0b80a51c0b85269afdaf/captum/attr/_models/base.py#L164), but it seems to fit if input is only a categorical feature and not a mix

**Comment by bilalsal** [comment]
Hi @sid-sundrani,

apologies for my delayed response.

A practical solution is to use Layer Attribution, i.e., attributing your output to an internal layer, instead of going all the way back to the input. if you select the embedding layer that concatenates both types of features, you will get the desired attributions. The attribution values for the parts coming from the categorical attribute will give you a clue about how important this attribute is for the specific prediction you are attributing. You can sum up the values (e.g. using L1 or L2 norms) if you desire to have a single number that quantifies this importance.

Hope this helps, happy holidays from the Captum team!
