### ISSUE TITLE
About the usage of function NeuronDeepLift and LayerDeepLift 

### ISSUE THREAD

**Issue by Timerunning** [pytorch/captum#829]
I found these two functions in the Captum API Reference. But please forgive my stupidity, so I don't understand what these two functions do, and how they differ from the captum.attr.DeepLift function. thanks

**Comment by bilalsal** [comment]
Hi @Timerunning ,

This is a great question!

Captum offers three modes for performing attribution. 

1. Primary attribution (as in standard `captum.attr.DeepLift`) helps you attribution a target neuron in the **output layer** to the input layer.
2. Layer attribution (as in `LayerDeepLift`) helps you attribution a target neuron also in the output layer, however, to an **intermediate layer** instead of the input layer. This is useful to understand how the features learned at this layer impact a specific prediction.
2. Neuron attribution (as in `NeuronDeepLift`) helps you attribute a **neuron in an intermediate layer** to the input layer. This helps you understand, which input features this neuron responds to. 

Figure 1 in [the Captum paper](https://arxiv.org/pdf/2009.07896.pdf) illustrates these three modes graphically.

Hope this helps - happy holidays from the Captum team!
