### ISSUE TITLE
How to use integrated gradient for hierarchical bert model

### ISSUE THREAD

**Issue by santoshTYSS** [pytorch/captum#883]
I have developed a Hierarchical Attention Model with Bert as word modelling component. Please find the entire code here.
https://colab.research.google.com/drive/185JYCldTFbF4tR3Cax25AKnW301VioFK#scrollTo=GSeOby8IqtGR

I was trying to invoke integrated gradients on this model but was facing with error. @NarineK , Kindly help me with how to proceed.

**Comment by NarineK** [comment]
Hi @santoshTYSS, the problem is that `docs` contains indices  and integrated gradients is trying to scale it by multiplying it with scalar scores. I think that you shouldn't use integrated gradients but instead layer integrated gradients which can be applied to scalar representations of those indices. Here we have examples of how to use Layer Integrated Gradients. https://captum.ai/tutorials/Bert_SQUAD_Interpret

**Comment by santoshTYSS** [comment]
Hi @NarineK , Thanks for reply; I have modified in above network using Layer integrated gradients but it throws the same error of requires grad fn. Kindly help me with it.
