### ISSUE TITLE
Erroneous unused differentiated Tensor when modifying return of detectron2 Faster RCNN

### ISSUE THREAD

**Issue by reedless** [pytorch/captum#901]
## 🐛 Bug

I was trying to apply Integrated Gradients to the detectron2 implementation of a COCO pre-trained Faster RCNN (specifically COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml). In order to get a tensor[K] of all the predicted probabilities for K classes, I sub-classed the appropriate classes and changed to output to the N rows of K predicted probabilities instead of N Instances, then proceeded to sum the N rows in my wrapper function.

However, running ig.attributes gives me
```
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    return_convergence_delta=True)
  File "/usr/local/lib/python3.6/dist-packages/captum/log/__init__.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/captum/attr/_core/integrated_gradients.py", line 291, in attribute
    method=method,
  File "/usr/local/lib/python3.6/dist-packages/captum/attr/_core/integrated_gradients.py", line 354, in _attribute
    additional_forward_args=input_additional_args,
  File "/usr/local/lib/python3.6/dist-packages/captum/_utils/gradient.py", line 118, in compute_gradients
    grads = torch.autograd.grad(torch.unbind(outputs), inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 225, in grad
    inputs, allow_unused, accumulate_grad=False)
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.
```

## To Reproduce

1. Minimal example can be found here: https://github.com/mreso/captum-detectron2/tree/simplifications
2. Follow the README to build Docker image and run `main.py`

## Expected behavior

ig.attributes runs and returns attributions, delta as expected

## Environment
Describe the environment used for Captum

Used the `nvidia/cuda:10.1-devel-ubuntu18.04` image, captum==0.4.1, torch==1.8.1+cu101, torchvision==0.9.1+cu101
Dockerfile and requirements.txt in repo above

## Additional Information
I've looked at the following issues and have verified that my issue does not overlap
https://github.com/pytorch/captum/issues/733 - input is a 3-channel image and nothing else, CNN should be using all of it
https://github.com/pytorch/captum/issues/303 - return tensor is created through `.clone()` and slicing, have tried `.detach()` on all other tensors to no avail
https://github.com/pytorch/captum/issues/139 - the abstractions around detectron2 have been resolved through subclassing

**Comment by NarineK** [comment]
@reedless, thank you for raising this issue. If I understand correctly this is the forward/predict function that you are using for this specific use case, isn't it ?
https://github.com/mreso/captum-detectron2/blob/simplifications/main.py#L70

I think that the problem might lie in the `torch.stack` call since it might be creating a new tensor that is not part of the inference. To validate this do you mind trying without calling stack, just returning `output[0].sum(dim=0)` for example, and seeing if you still see the error?

https://github.com/mreso/captum-detectron2/blob/simplifications/main.py#L73

**Comment by reedless** [comment]
I get `AssertionError: Cannot choose target column with output shape torch.Size([80]).`, and fixed that by modifying the return to `output[0].sum(dim=0).unsqueeze(0)` after checking the sizes. However, I still get `RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.` after trying that

**Comment by NarineK** [comment]
@reedless, we don't use dockers I didn't set up the project on my development machine. A question: What is the inference method that you are passing to Captum ? This one takes dict. I assume it's not this one:
https://github.com/mreso/captum-detectron2/blob/simplifications/modified_rcnn.py#L87

Do you mind pointing me to the inference method that is passed to Captum ? I think that probably the inputs that we are passing to captum aren't used in the model's forward pass. I wanted to check how the inputs are used in the forward function.

**Comment by reedless** [comment]
Apologies, I copied over the source code from detectron2 and did not edit the original comments, leading to this confusion. Both the inference and forward function should take in `batched_inputs: List[torch.Tensor]`. 

Just to check, should I be passing the forward function or the inference function to Captum? Due to setting `model.eval()` at the start of the code, I assumed that they would be the same, but if they are not then that could be the issue.

**Comment by reedless** [comment]
Let me just merge the branches and clean up the comments, then the most updated repo would be at https://github.com/reedless/captum-detectron2

**Comment by NarineK** [comment]
Thank you, @reedless! I'll take a look

**Comment by NarineK** [comment]
@reedless, I see that `preprocess_image`  is still taking a list of tensors. Isn't it being called from the inference with a tensor  in rcnn.py ?

https://github.com/facebookresearch/detectron2/blob/main/detectron2/modeling/meta_arch/rcnn.py#L199

Is above inference function being called in `main.py`? I need a code pointer to inference function used in main.py. I feel that in the inference function, new tensors are being recreated that's why we can't attribute to the `input_`. In order to confirm that I need a code pointer to exact inference function used.

In case new tensors are being recreated and used internally in the inference we can use LayerIntegratedGradients and attribute to inputs or outputs of specific layers.

**Comment by reedless** [comment]
My bad, `preprocess_image` is indeed called with a tensor. The code pointer you have linked to detectron2's rcnn is also indeed the inference function used.

Please let me know when you manage to find where new tensors are being recreated in `inference`!

**Comment by NarineK** [comment]
Hi @reedless, I debugged this case with LayerGradientsXActivation. I computed the gradients w.r.t. backbone layer. When I compute the gradients w.r.t. layer inputs to backbone then it works. This shows that the issue lies in image preprocessing
```
 lg = LayerGradientXActivation(wrapper_model, wrapper_model.model.backbone) 
 attributions = lg.attribute(input_,
                                         target=pred_class, attribute_to_layer_input=True)
```

I think that probably somewhere here it is creating new tensors:
https://github.com/mreso/captum-detectron2/blob/simplifications/main.py#L41

In  terms of specifically, IG, we need to think that this model architecture will work because IG is scaling the inputs by number of steps. When I was scaling the inputs, I noticed that that scaling isn't passed down to further layers. I think it compresses the inputs when it is creating the boxes. You can, for example, try simple saliency, occlusion or feature ablation instead of IG. For IG we need to debug further and find out if the input scaling is being passed down to next layers of the model.

**Comment by reedless** [comment]
Ah yes, I think it's this line 
https://github.com/reedless/captum-detectron2/blob/main/modified_image_list.py#L61

For IG, do you mean that when the algorithm passes the default 50 inputs on the first forward pass, the next layers of the model should keep the predictions for the 50 inputs entirely separate (i.e. 50 x 1000 x 81) rather than merge them together (i.e. 50000 x 81)?

**Comment by NarineK** [comment]
@reedless, yes, exactly, the first dimension corresponds to number of examples. IG scales input by generating 50 perturbations of given input examples. The output is expected to be for 50 samples as well since we compute the integral of the gradients w.r.t. all those samples. You can check that in the IG paper.

**Comment by reedless** [comment]
Hi @NarineK, never mind, I figured out what it is used for :P It is a proxy for the "correctness" of the attributions.

For future users facing this issue, the patches to detectron2 code found [here](https://github.com/reedless/captum-detectron2/commit/147b779e7fb84df3c2b4ae928d165c0967e8cd84) would allow you to run Integrated Gradients and GradientSHAP, then convert the attributions into a mask and save it on the input image.
