### ISSUE TITLE
Using TCAV for Bert Sentiment Analysis Model | Discrepancy in Captum

### ISSUE THREAD

**Issue by basselmawzi** [pytorch/captum#918]
## ❓ Questions and Help

Hello, 

I was trying to calculate the TCAV scores for a text classification Bert model. I loaded the model from hugging face and I initialized TCAV using the same method as indicated in the tutorial on captum's website. 

It turns out that for TCAV, I need to pass a list of layer names and NOT layer modules. How can I name layers for bert and pass them to TCAV in order to calculate the TCAV scores? 

Also, why is there a discrepancy between most of captum's methods and TCAV? Most methods in captum take a list of torch modules as their layers but tcav takes a list of layer names. 

Your help is appreciated, 
Thanks

**Comment by NarineK** [comment]
Hi @basselmawzi, thank you for the question. The reason that here we want full hierarchical name of the layer(such as `modelx.mlp.linear`) is because we save the Activations and CAVs under layer's full hierarchical name on the disk (otherwise there are many linear layers in any given model) and reload them in order to reuse. 

Given a layer such as `modelx.mlp.linear` we cannot backtrack parent layers from given linear layer in order to identify its full hierarchical path for given any layer; so that we can use it as an identifier for saving the CAVs and Activations. We have to either provide this path as string `modelx.mlp.linear` or we have to traverse the entire model in order to find that specific linear layer. Since providing  string path `modelx.mlp.linear` is easier, we chose that option.

Let me know if this is not clear.

**Comment by basselmawzi** [comment]
Okay thank you!
