### ISSUE TITLE
Make model a separate argument in attribution

### ISSUE THREAD

**Issue by ZhiyuanChen** [pytorch/captum#923]
## 🚀 Feature

Make model a separate argument in attribution

## Motivation

Complex models often requires custom helper function for attribution. For example, [BERT tutorials](https://captum.ai/tutorials/Bert_SQUAD_Interpret2) defined `squad_pos_forward_func` and `predict` for attribution.
However, not all attributions support helper function like this, including `LayerDeepLift` and `LayerLRP', they assume the first argument is a `nn.Module`. Consider pass model as a saparate argument.

**Comment by NarineK** [comment]
@ZhiyuanChen, nn.Module is a special case of Callable. In order to keep the type hints clean we use the name `forward_func` but we see `nn.Module` as `Callable` as well. The name `forward_func` might be a bit confusing but it is meant to represent nn.Module as well. If we make `nn.Module` another argument it will make the API unnecessary convoluted.
https://github.com/pytorch/captum/blob/master/captum/attr/_core/integrated_gradients.py#L50
