### ISSUE TITLE
NeuronAttribution methods applied to embedding analysis

### ISSUE THREAD

**Issue by mabelc** [pytorch/captum#925]
Hi,

I want to get attribution with respect to each input feature in a classification problem where I am only interested in the embeddings.
I started using NeuronGradient to analyze every neuron in the embedding. The results are good but I got a performance issue because I am calling the corresponding attribute method for every neuron in the representation and it takes around 30 seconds to complete. It becomes hours when analyzing several inputs.

Is there any way to accelerate this computation within Captum API?

Thanks

**Comment by vivekmig** [comment]
Hi @mabelc , there are a few ways of improving this performance for this:
1. Compute layer attribution first and identify neurons which have larger impact on the model output. Based on this, you can compute neuron attribution for neurons with attribution exceeding a particular threshold rather than all neurons, which may include a large number with limited impact on the model output.
2. You can obtain neuron attributions for a group of neurons together by providing neuron_selector as a Callable which aggregates the group of neurons you want attributions for (e.g. sum). You can first compute neuron attributions for larger groups of neurons and then consider neurons individually as needed.
3. You can look into batching multiple input examples together for attribution. Alternatively, you may also be able to use the neuron_selector functionality to batch attributions for multiple neurons (on the same input example) together based on the memory constraints of your model. To do this, you can expand the input batch k times, and within your neuron_selector function, select a different neuron from each of the k inputs. 

Hope this helps!

**Comment by mabelc** [comment]
Thanks! I will try those solutions

**Comment by Vitor-Almeida** [comment]
Hi @mabelc , if you don't mind, can you share your code? I'm trying to get the Neuron Activations by input token of a BERT model trained in a text classification teask , and I couldn't find any resource.
