### ISSUE TITLE
CUDA out of Memory errors

### ISSUE THREAD

**Issue by basselmawzi** [pytorch/captum#930]
## ❓ Questions and Help

Hello, 

I have been trying to use captum for calculating TCAV scores for BERT (I am using a loaded model for sentiment analysis from hugging face). I was able to calculate get these scores in some cases, but in other cases I face the CUDA out of memory errors. To be more specific, I am facing such errors in the following two cases: 

1) When I try to pass all Bert encoder layers to the TCAV class (11 layers in total). In other words, I pass all layers to initialize TCAV and it initializes successfully. However when I call the .interpert method on the same input examples in the tutorial, I get this error.

2) when I increase the number of input samples to the tcav.interpret method to more than 10 samples I face the same error. 

Can you please provide some guidance in order to avoid such errors?

**Comment by NarineK** [comment]
@basselmawzi, since we are using Sklearn to train a model that computes the CAVs, it can be that the number of activations don't fit into the memory. sklearn runs only on CPU. If that is the issue then you can define your own classifier that can be trained on GPUs and is more scalable. you can plug that in into TCAV as an additional argument. https://captum.ai/api/concept.html

I'm not exactly clear if that is the main issue. I think  that you need to debug and see were exactly OOM happens.

**Comment by basselmawzi** [comment]
okay thank you!
